import { DayOfWeek, Habit, RealmProgression, RealmType, TechUnlock } from './types';

export interface RealmGoalPreset {
  title: string;
  description: string;
  category: 'Health' | 'Mind' | 'Career' | 'Fitness' | 'Creativity' | 'Routine';
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Epic';
  targetTimeOfDay: 'Morning' | 'Afternoon' | 'Evening' | 'Anytime';
  growthImpact: string;
}

export interface RealmMeta {
  id: RealmType;
  name: string;
  title: string;
  tagline: string;
  description: string;
  icon: string;
  accentColor: string;
  glowColor: string;
  resourceName: string;
  resourceIcon: string;
  primaryGoalTitle: string;
  primaryGoalDescription: string;
  goalFocusAreas: string[];
  goalPresets: RealmGoalPreset[];
  stageNames: [string, string, string, string, string];
  stageDescriptions: [string, string, string, string, string];
  availableStructures: {
    itemKey: string;
    name: string;
    description: string;
    tierRequired: number;
    icon: string;
    cost: number;
    lore: string;
  }[];
}

export const REALM_DEFINITIONS: Record<RealmType, RealmMeta> = {
  garden: {
    id: 'garden',
    name: 'Celestial Sanctuary',
    title: 'Botanical Garden of Serenity',
    tagline: 'Cultivate rare flora, sacred blossoms, and ancient trees of vitality.',
    description: 'Every completed habit nurtures the soil with radiant morning dew and golden sunlight, evolving humble seeds into a thriving mystical sanctuary.',
    icon: 'Flower2',
    accentColor: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    resourceName: 'Sunlit Dew',
    resourceIcon: 'Droplets',
    primaryGoalTitle: 'Reawaken the Eternal Tree of Life',
    primaryGoalDescription: 'Grow your botanical garden from humble sprouts into a radiant sanctuary of peace, health, and vitality.',
    goalFocusAreas: ['Physical Hydration', 'Morning Sunlight', 'Healthy Nutrition', 'Restful Sleep', 'Nature Walks'],
    goalPresets: [
      {
        title: 'Morning 750ml Hydration & Dawn Light',
        description: 'Drink a large glass of pure water and soak in 10 minutes of natural outdoor sunlight.',
        category: 'Health',
        difficulty: 'Easy',
        targetTimeOfDay: 'Morning',
        growthImpact: 'Irrigates the sprout nursery with fresh morning dew',
      },
      {
        title: 'Wholesome Plant-Rich Whole Food Diet',
        description: 'Eat at least 2 servings of fresh vegetables or fruit and minimize processed sugar.',
        category: 'Health',
        difficulty: 'Medium',
        targetTimeOfDay: 'Afternoon',
        growthImpact: 'Nourishes the blooming lotus pond with vital nutrients',
      },
      {
        title: 'Evening Digital Sunset & Sleep Sanctuary',
        description: 'Shut down blue screens 45 minutes before sleep and maintain 8 hours of restorative rest.',
        category: 'Routine',
        difficulty: 'Medium',
        targetTimeOfDay: 'Evening',
        growthImpact: 'Channels moonlit dew to the glowing bioluminescent willow',
      },
      {
        title: '10,000 Steps Outdoor Nature Walk',
        description: 'Immerse in the outdoors, breathe clean air, and accumulate 10,000 total steps.',
        category: 'Fitness',
        difficulty: 'Hard',
        targetTimeOfDay: 'Afternoon',
        growthImpact: 'Awakens the deep root network of the World Tree of Life',
      },
    ],
    stageNames: [
      'Stage I: Sprout Clearing',
      'Stage II: Blooming Grove',
      'Stage III: Luminescent Orchard',
      'Stage IV: Sacred Arboretum',
      'Stage V: Eternal Tree of Life',
    ],
    stageDescriptions: [
      'A quiet patch of fertile moss where the first green sprouts break through the earth.',
      'Wildflowers and crystal lilies blossom in vibrant harmony, attracting humming spirit bees.',
      'Bioluminescent weeping willows and lotus ponds illuminate the evening canopy.',
      'Ancient monoliths entwined with golden ivy amplify nature’s restorative pulse.',
      'The majestic World Tree towers into the clouds, radiating perpetual tranquility and wisdom.',
    ],
    availableStructures: [
      {
        itemKey: 'sprout_bed',
        name: 'Zen Herb Bed',
        description: 'Cultivates calming peppermint and lavender.',
        tierRequired: 1,
        icon: 'Sprout',
        cost: 30,
        lore: 'Tended with daily morning routines, these herbs grant clarity of mind.',
      },
      {
        itemKey: 'crystal_lotus',
        name: 'Moonlight Lotus Pond',
        description: 'A serene reflective pond with glowing water lilies.',
        tierRequired: 2,
        icon: 'Sparkles',
        cost: 75,
        lore: 'Blooms only when your focus is unbroken, shimmering under twilight skies.',
      },
      {
        itemKey: 'sakura_shrine',
        name: 'Harmonic Sakura Grove',
        description: 'Blossoms swirl in gentle updrafts of pure positive energy.',
        tierRequired: 3,
        icon: 'Flower2',
        cost: 150,
        lore: 'Ancient monks planted these trees to mark consecutive weeks of discipline.',
      },
      {
        itemKey: 'spirit_willow',
        name: 'Bioluminescent Willow',
        description: 'Glows with emerald luminescence, feeding off your steady habits.',
        tierRequired: 4,
        icon: 'Trees',
        cost: 250,
        lore: 'Its roots delve deep into the bedrock of consistent habits.',
      },
      {
        itemKey: 'tree_of_life',
        name: 'Grand Mother Tree',
        description: 'The pinnacle of botanical harmony and life energy.',
        tierRequired: 5,
        icon: 'TreePine',
        cost: 500,
        lore: 'A timeless sentinel that nourishes the entire sanctuary.',
      },
    ],
  },

  military: {
    id: 'military',
    name: 'Aegis Vanguard',
    title: 'Tactical Defense Stronghold',
    tagline: 'Fabricate heavy battle mechs, orbital defense cannons, and cyber warfare tech.',
    description: 'Transform small daily disciplines into an impenetrable high-tech fortress equipped with autonomous drones, mechanized armor, and plasma grids.',
    icon: 'ShieldAlert',
    accentColor: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    resourceName: 'Titanium Alloys',
    resourceIcon: 'Cpu',
    primaryGoalTitle: 'Deploy the Apex Orbital Defense Citadel',
    primaryGoalDescription: 'Build an impenetrable stronghold through grueling physical training, iron discipline, and tactical execution.',
    goalFocusAreas: ['Strength & Weightlifting', 'Cardio & HIIT Drills', 'Cold Showers & Resilience', 'Early Wake-up Drills', 'Clean Diet Protocol'],
    goalPresets: [
      {
        title: '0600 Tactical Reveille & Pushup Battery',
        description: 'Wake up promptly at the alarm and execute 50 pushups and 50 air squats.',
        category: 'Fitness',
        difficulty: 'Medium',
        targetTimeOfDay: 'Morning',
        growthImpact: 'Supplies Titanium plating for perimeter sentry turrets',
      },
      {
        title: '45-Minute Heavy Iron / Strength Protocol',
        description: 'Complete a structured strength session targeting compound resistance lifts.',
        category: 'Fitness',
        difficulty: 'Hard',
        targetTimeOfDay: 'Afternoon',
        growthImpact: 'Forges heavy mechanized armor plates for the Titan War Mech',
      },
      {
        title: '5km Tactical Endurance Run',
        description: 'Run 5 kilometers maintaining consistent cadence and heart rate discipline.',
        category: 'Fitness',
        difficulty: 'Hard',
        targetTimeOfDay: 'Morning',
        growthImpact: 'Calibrates telemetry for long-range autonomous hover drones',
      },
      {
        title: 'Zero Procrastination 2-Minute Rule',
        description: 'Immediately tackle any mission taking under 2 minutes without delay.',
        category: 'Routine',
        difficulty: 'Easy',
        targetTimeOfDay: 'Anytime',
        growthImpact: 'Hardens perimeter firewalls against tactical breaches',
      },
    ],
    stageNames: [
      'Stage I: Forward Recon Post',
      'Stage II: Fortified Perimeter',
      'Stage III: Mechanized Outpost',
      'Stage IV: Cyber Citadel',
      'Stage V: Orbital Defense Super-Fortress',
    ],
    stageDescriptions: [
      'A rugged forward operating base with radar telemetry and basic sandbag barricades.',
      'Reinforced blast walls, automated sentry turrets, and armored scout buggies.',
      'Drone deployment bays, vehicle maintenance hangars, and plasma generators.',
      'High-altitude stealth radars, energy shield domes, and AI tactical networks.',
      'A formidable planetary bastion with dual orbital railguns and heavy mech divisions.',
    ],
    availableStructures: [
      {
        itemKey: 'sentry_turret',
        name: 'Twin-Link Laser Sentry',
        description: 'Automated turret that scans for procrastination breaches.',
        tierRequired: 1,
        icon: 'Crosshair',
        cost: 35,
        lore: 'Rapid-firing laser battery providing 24/7 perimeter protection.',
      },
      {
        itemKey: 'radar_dish',
        name: 'Phased Array Radar',
        description: 'Detects long-range objectives and habit targets.',
        tierRequired: 2,
        icon: 'Radio',
        cost: 80,
        lore: 'Scans the horizon for upcoming deadlines and goal milestones.',
      },
      {
        itemKey: 'drone_bay',
        name: 'Sky-Eye Drone Bay',
        description: 'Launches autonomous quadcopters for aerial recon.',
        tierRequired: 3,
        icon: 'Plane',
        cost: 160,
        lore: 'These nimble UAVs patrol your task queue day and night.',
      },
      {
        itemKey: 'titan_mech',
        name: 'Aegis-IV Titan Mech',
        description: 'Heavy bipedal war mech powered by streak energy.',
        tierRequired: 4,
        icon: 'Bot',
        cost: 280,
        lore: 'Piloted by commanders who hold unbreakable daily streaks.',
      },
      {
        itemKey: 'orbital_cannon',
        name: 'Ion Storm Orbital Cannon',
        description: 'Planetary-scale defense platform firing focused particle beams.',
        tierRequired: 5,
        icon: 'Zap',
        cost: 550,
        lore: 'The ultimate symbol of unwavering discipline and tactical dominance.',
      },
    ],
  },

  town: {
    id: 'town',
    name: 'Aethelgard',
    title: 'Metropolis of the High Kings',
    tagline: 'Construct cozy cottages, bustling market squares, and royal castles.',
    description: 'Each daily triumph lays cobblestones, raises stone towers, and welcomes merchants, blacksmiths, and citizens into your flourishing realm.',
    icon: 'Castle',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    resourceName: 'Royal Timber & Gold',
    resourceIcon: 'Coins',
    primaryGoalTitle: 'Erect the Imperial Crown Metropolis',
    primaryGoalDescription: 'Build a flourishing kingdom through financial prudence, craft mastery, and noble community leadership.',
    goalFocusAreas: ['Budgeting & Savings', 'Workspace Cleanliness', 'Community Kindness', 'Daily Planning', 'Skill Craftsmanship'],
    goalPresets: [
      {
        title: 'Daily Financial Treasury Log',
        description: 'Track all expenses and set aside daily savings into the treasury vault.',
        category: 'Routine',
        difficulty: 'Easy',
        targetTimeOfDay: 'Evening',
        growthImpact: 'Funds the artisan craft guild and market stalls',
      },
      {
        title: 'Sanctuary Tidy & Organization',
        description: 'Spend 15 minutes organizing your physical desk, kitchen, or living room.',
        category: 'Routine',
        difficulty: 'Easy',
        targetTimeOfDay: 'Evening',
        growthImpact: 'Lays clean cobblestones throughout the residential district',
      },
      {
        title: 'Noble Deed / Friend Connection',
        description: 'Reach out to a family member, mentor, or friend to offer support or gratitude.',
        category: 'Routine',
        difficulty: 'Medium',
        targetTimeOfDay: 'Anytime',
        growthImpact: 'Attracts new happy citizens to settle in the town',
      },
      {
        title: 'Mastery of Craft Practice (1 Hour)',
        description: 'Dedicate 60 focused minutes to honing an artisan or professional craft.',
        category: 'Career',
        difficulty: 'Epic',
        targetTimeOfDay: 'Morning',
        growthImpact: 'Raises the towering battlements of the Grand Castle',
      },
    ],
    stageNames: [
      'Stage I: Pioneer Settlement',
      'Stage II: Thriving Village',
      'Stage III: Market Township',
      'Stage IV: Walled City-State',
      'Stage V: Imperial Crown Metropolis',
    ],
    stageDescriptions: [
      'A warm campfire surrounded by timber cabins and stone hearths.',
      'Cobblestone pathways, watermills, bakery chimneys, and market stalls.',
      'Garrisoned stone walls, guild halls, clock towers, and town fountain.',
      'Grand cathedral, majestic libraries, arched aqueducts, and noble estates.',
      'A legendary gilded capital with royal palaces, soaring spires, and grand monuments.',
    ],
    availableStructures: [
      {
        itemKey: 'cozy_cottage',
        name: 'Artisan Cottage',
        description: 'Warm timber and stone house for hardworking craftspeople.',
        tierRequired: 1,
        icon: 'Home',
        cost: 30,
        lore: 'Smoke curls from the chimney as masters craft your daily tools.',
      },
      {
        itemKey: 'grain_windmill',
        name: 'Highland Windmill',
        description: 'Grinds harvest grain into golden flour with steady rotation.',
        tierRequired: 2,
        icon: 'Wind',
        cost: 70,
        lore: 'Turns tirelessly like your daily morning habits.',
      },
      {
        itemKey: 'market_square',
        name: 'Bustling Guild Market',
        description: 'Merchants trade exotic goods and royal supplies.',
        tierRequired: 3,
        icon: 'Store',
        cost: 140,
        lore: 'The commercial heart of your burgeoning city.',
      },
      {
        itemKey: 'clockwork_tower',
        name: 'Great Clockwork Spire',
        description: 'Chimes on the hour to celebrate daily victories.',
        tierRequired: 4,
        icon: 'Clock',
        cost: 260,
        lore: 'Master engineers calibrated this tower to align with your daily schedule.',
      },
      {
        itemKey: 'royal_castle',
        name: 'Castle of the Grand Monarch',
        description: 'Towering stone battlements and gilded crown banners.',
        tierRequired: 5,
        icon: 'Castle',
        cost: 500,
        lore: 'Seat of the monarch whose kingdom was forged one habit at a time.',
      },
    ],
  },

  space: {
    id: 'space',
    name: 'Astra Zenith',
    title: 'Orbital Deep-Space Colony',
    tagline: 'Build bio-domes, terraforming engines, solar arrays, and warp gates.',
    description: 'Channel your focus to pioneer the final frontier: assemble modular orbital rings, launch deep-space probes, and explore distant galaxies.',
    icon: 'Rocket',
    accentColor: '#8b5cf6',
    glowColor: 'rgba(139, 92, 246, 0.4)',
    resourceName: 'Antimatter Cells',
    resourceIcon: 'Atom',
    primaryGoalTitle: 'Construct the Interstellar Warp Gateway',
    primaryGoalDescription: 'Venture into the cosmic frontier by powering quantum reactors through coding sprints and deep technical mastery.',
    goalFocusAreas: ['Software Engineering', 'System Architecture', 'Algorithmic Problem Solving', 'Technical RFCs', 'Zero-Distraction Sprints'],
    goalPresets: [
      {
        title: 'Deep Work Coding / Engineering Sprint',
        description: '45 minutes of hyper-focused software development with phone on do-not-disturb.',
        category: 'Career',
        difficulty: 'Epic',
        targetTimeOfDay: 'Morning',
        growthImpact: 'Fuels the antimatter core and powers orbital quantum computers',
      },
      {
        title: 'Code Review & Clean Git Commits',
        description: 'Review Pull Requests, write automated tests, and submit well-documented commits.',
        category: 'Career',
        difficulty: 'Medium',
        targetTimeOfDay: 'Afternoon',
        growthImpact: 'Maintains telemetry link with deep space exploratory probes',
      },
      {
        title: 'Algorithm & Systems Study (30m)',
        description: 'Solve 1 complex coding challenge or read an in-depth systems engineering paper.',
        category: 'Mind',
        difficulty: 'Hard',
        targetTimeOfDay: 'Evening',
        growthImpact: 'Calculates orbital trajectories for deep-space starships',
      },
      {
        title: 'Ship Logs & Documentation Writing',
        description: 'Document your codebase architecture and write clear developer setup notes.',
        category: 'Career',
        difficulty: 'Easy',
        targetTimeOfDay: 'Anytime',
        growthImpact: 'Optimizes life support subsystems inside lunar bio-domes',
      },
    ],
    stageNames: [
      'Stage I: Orbital Waypoint',
      'Stage II: Pressurized Habitat',
      'Stage III: Biosphere Station',
      'Stage IV: Fleet Drydock',
      'Stage V: Interstellar Warp Gateway',
    ],
    stageDescriptions: [
      'A solitary survey probe and solar collector orbiting a blue exoplanet.',
      'Pressurized living modules, hydroponic pods, and communication relays.',
      'Rotating gravity rings, lush greenhouse bio-domes, and fusion reactors.',
      'Massive starship construction docks and quantum research laboratories.',
      'A hyper-dimensional warp gate opening pathways to uncharted star systems.',
    ],
    availableStructures: [
      {
        itemKey: 'solar_panel',
        name: 'Helios Solar Collector',
        description: 'Harvests stellar radiation for zero-emission energy.',
        tierRequired: 1,
        icon: 'Sun',
        cost: 35,
        lore: 'Absorbs the raw energy of consistent daily effort.',
      },
      {
        itemKey: 'hydroponic_dome',
        name: 'Lunar Hydro-Dome',
        description: 'Grows oxygen-producing crops in zero gravity.',
        tierRequired: 2,
        icon: 'Globe',
        cost: 85,
        lore: 'Sustainable life support sustained by your uninterrupted streaks.',
      },
      {
        itemKey: 'starship_pad',
        name: 'Orbital Launch Bay',
        description: 'Prepares explorer craft for deep space scouting missions.',
        tierRequired: 3,
        icon: 'Rocket',
        cost: 170,
        lore: 'Ships depart on interstellar voyages whenever a streak hits 7 days.',
      },
      {
        itemKey: 'quantum_reactor',
        name: 'Singularity Core',
        description: 'Harnesses micro-black holes for infinite propulsion.',
        tierRequired: 4,
        icon: 'Compass',
        cost: 300,
        lore: 'The apex of futuristic propulsion technology.',
      },
      {
        itemKey: 'warp_gate',
        name: 'Hyper-Warp Ring',
        description: 'Bends space-time to travel across the cosmos in seconds.',
        tierRequired: 5,
        icon: 'Orbit',
        cost: 580,
        lore: 'Connecting your personal achievements with the far reaches of the universe.',
      },
    ],
  },

  arcane: {
    id: 'arcane',
    name: 'Eldritch Spire',
    title: 'Citadel of the Arcane Masters',
    tagline: 'Summon floating rune crystals, brew legendary potions, and master spell grimoires.',
    description: 'Transmute daily willpower into raw arcane power, raising floating towers, mystic cauldrons, and astral observatories.',
    icon: 'Wand2',
    accentColor: '#ec4899',
    glowColor: 'rgba(236, 72, 153, 0.4)',
    resourceName: 'Aether Shards',
    resourceIcon: 'Sparkle',
    primaryGoalTitle: 'Awaken the Grand Archmage Nexus',
    primaryGoalDescription: 'Transmute internal willpower into transcendent magic through meditation, philosophical reading, and creative creation.',
    goalFocusAreas: ['Mindfulness Meditation', 'Philosophical Reading', 'Journaling & Reflection', 'Creative Writing / Art', 'Astral Visualization'],
    goalPresets: [
      {
        title: '20-Minute Deep Mindful Meditation',
        description: 'Sit in silence, observe thoughts without judgment, and center your breathing.',
        category: 'Mind',
        difficulty: 'Medium',
        targetTimeOfDay: 'Morning',
        growthImpact: 'Charges levitating mana crystals with pure elemental aether',
      },
      {
        title: 'Read 20 Pages of Enlightening Literature',
        description: 'Immerse in classic books, philosophy, or psychology and write 3 reflections.',
        category: 'Mind',
        difficulty: 'Medium',
        targetTimeOfDay: 'Evening',
        growthImpact: 'Inscribes ancient glyphs into the Forbidden Grimoire Vault',
      },
      {
        title: 'Creative Flow Alchemy (Drawing / Writing)',
        description: 'Spend 30 uninterrupted minutes creating original art, prose, or music.',
        category: 'Creativity',
        difficulty: 'Hard',
        targetTimeOfDay: 'Afternoon',
        growthImpact: 'Stirs bubbling vapors in the Philosopher’s Cauldron',
      },
      {
        title: 'Nightly Reflection & Gratitude Runes',
        description: 'Write down 3 daily victories, 1 lesson learned, and 1 positive affirmation.',
        category: 'Mind',
        difficulty: 'Easy',
        targetTimeOfDay: 'Evening',
        growthImpact: 'Harmonizes celestial orbits in the Astral Orrery Observatory',
      },
    ],
    stageNames: [
      'Stage I: Apprentice Circle',
      'Stage II: Alchemy Laboratory',
      'Stage III: Mystic Spires',
      'Stage IV: Astral Observatory',
      'Stage V: Archmage Grand Nexus',
    ],
    stageDescriptions: [
      'An ancient stone summoning circle glowing with faint violet runes.',
      'Bubbling potion cauldrons, herbal grimoires, and glowing mana crystals.',
      'Floating stone towers suspended by telekinetic ley lines and spell wards.',
      'Celestial astrolabes charting astral convergences and star omens.',
      'The Grand Archmage Nexus where raw creation magic flows like liquid light.',
    ],
    availableStructures: [
      {
        itemKey: 'potion_cauldron',
        name: 'Philosopher’s Cauldron',
        description: 'Brews elixirs of boundless energy and motivation.',
        tierRequired: 1,
        icon: 'FlaskConical',
        cost: 30,
        lore: 'Infused with distilled willpower from daily habit completions.',
      },
      {
        itemKey: 'crystal_pillar',
        name: 'Levitating Mana Crystal',
        description: 'Channels elemental energies into protective spell shields.',
        tierRequired: 2,
        icon: 'Gem',
        cost: 75,
        lore: 'Resonates in harmony with steady meditation and study routines.',
      },
      {
        itemKey: 'astral_telescope',
        name: 'Orrery of the Cosmos',
        description: 'Tracks celestial alignments to predict auspicious days.',
        tierRequired: 3,
        icon: 'Eye',
        cost: 155,
        lore: 'Reveals future potential when your habits remain unclouded.',
      },
      {
        itemKey: 'spell_vault',
        name: 'Forbidden Grimoire Vault',
        description: 'Houses tomes of ancient knowledge and mastered arts.',
        tierRequired: 4,
        icon: 'BookOpen',
        cost: 290,
        lore: 'Contains the secret spells of perpetual focus and deep work.',
      },
      {
        itemKey: 'archmage_nexus',
        name: 'Astral Archmage Nexus',
        description: 'Pinnacle of sorcery where thought transforms reality.',
        tierRequired: 5,
        icon: 'Flame',
        cost: 540,
        lore: 'The legendary seat of the High Archmage who conquered all daily goals.',
      },
    ],
  },
};

export const INITIAL_TECH_TREE: TechUnlock[] = [
  // Garden
  { id: 'g_1', realm: 'garden', name: 'Rapid Germination', description: 'Increases dew harvest by 20% on morning habits.', tier: 1, cost: 40, resourceCost: 20, icon: 'Droplets', unlocked: true, bonusEffect: '+20% morning Dew' },
  { id: 'g_2', realm: 'garden', name: 'Photosynthetic Surge', description: 'Daily habits completed before noon grant +15 XP.', tier: 2, cost: 90, resourceCost: 50, icon: 'Sun', unlocked: false, bonusEffect: '+15 XP before noon' },
  { id: 'g_3', realm: 'garden', name: 'Bioluminescent Bloom', description: 'Streak rewards are increased by 25%.', tier: 3, cost: 180, resourceCost: 100, icon: 'Sparkles', unlocked: false, bonusEffect: '+25% streak rewards' },
  { id: 'g_4', realm: 'garden', name: 'Deep Root Resilience', description: 'First missed day each week is automatically protected without breaking streak.', tier: 4, cost: 320, resourceCost: 180, icon: 'Shield', unlocked: false, bonusEffect: 'Free weekly streak save' },
  { id: 'g_5', realm: 'garden', name: 'Avatar of Nature', description: 'All garden structures generate +50% passive energy.', tier: 5, cost: 600, resourceCost: 350, icon: 'TreePine', unlocked: false, bonusEffect: '+50% realm output' },

  // Military
  { id: 'm_1', realm: 'military', name: 'Tactical Discipline', description: 'Workout & fitness habits yield double Titanium.', tier: 1, cost: 40, resourceCost: 20, icon: 'Dumbbell', unlocked: true, bonusEffect: '2x Fitness Titanium' },
  { id: 'm_2', realm: 'military', name: 'Automated Logistical Hub', description: 'All base defense structures cost 15% less resources.', tier: 2, cost: 95, resourceCost: 55, icon: 'Wrench', unlocked: false, bonusEffect: '-15% building cost' },
  { id: 'm_3', realm: 'military', name: 'Overcharge Reactor', description: 'Hard & Epic habits award an extra streak shield chance.', tier: 3, cost: 190, resourceCost: 110, icon: 'Zap', unlocked: false, bonusEffect: 'Bonus shield drop rate' },
  { id: 'm_4', realm: 'military', name: 'Orbital Telemetry Link', description: 'Increases all XP gains across all habits by 20%.', tier: 4, cost: 350, resourceCost: 200, icon: 'Radio', unlocked: false, bonusEffect: '+20% XP global' },
  { id: 'm_5', realm: 'military', name: 'Apex Warforge', description: 'Unlocks the legendary Titan Commander avatar badge.', tier: 5, cost: 650, resourceCost: 400, icon: 'Crown', unlocked: false, bonusEffect: 'Commander title & badge' },

  // Town
  { id: 't_1', realm: 'town', name: 'Merchant Guild License', description: 'Earn +5 bonus Gold Coins per completed habit.', tier: 1, cost: 35, resourceCost: 20, icon: 'Coins', unlocked: true, bonusEffect: '+5 Gold Coins' },
  { id: 't_2', realm: 'town', name: 'Cobblestone Infrastructure', description: 'Routine habits grant +25% town progression points.', tier: 2, cost: 85, resourceCost: 45, icon: 'Layers', unlocked: false, bonusEffect: '+25% Routine points' },
  { id: 't_3', realm: 'town', name: 'Grand Harvest Festival', description: 'Completing all daily habits triggers a 1.5x coin burst.', tier: 3, cost: 175, resourceCost: 95, icon: 'PartyPopper', unlocked: false, bonusEffect: '1.5x Daily clear bonus' },
  { id: 't_4', realm: 'town', name: 'Royal Charter of Freedom', description: 'Unlocks custom cosmetic decorations in the shop.', tier: 4, cost: 310, resourceCost: 170, icon: 'FileText', unlocked: false, bonusEffect: 'Unlock royal deco' },
  { id: 't_5', realm: 'town', name: 'Golden Sovereign Realm', description: 'The town square holds continuous celebrations.', tier: 5, cost: 580, resourceCost: 320, icon: 'Castle', unlocked: false, bonusEffect: 'Infinite jubilee theme' },

  // Space
  { id: 's_1', realm: 'space', name: 'Zero-G Optimization', description: 'Coding & learning habits yield +30% Antimatter.', tier: 1, cost: 45, resourceCost: 25, icon: 'Code', unlocked: true, bonusEffect: '+30% Study Antimatter' },
  { id: 's_2', realm: 'space', name: 'Solar Grid Hyper-Feed', description: 'Afternoon completions grant double energy cells.', tier: 2, cost: 100, resourceCost: 60, icon: 'SunMedium', unlocked: false, bonusEffect: '2x Afternoon energy' },
  { id: 's_3', realm: 'space', name: 'Quantum Computation', description: 'Streaks charge a quantum combo meter for mega XP bursts.', tier: 3, cost: 210, resourceCost: 120, icon: 'Cpu', unlocked: false, bonusEffect: 'Quantum combo meter' },
  { id: 's_4', realm: 'space', name: 'Tachyon Communication', description: 'AI Habit Coach gives advanced predictive recommendations.', tier: 4, cost: 360, resourceCost: 210, icon: 'Sparkle', unlocked: false, bonusEffect: 'Advanced AI insights' },
  { id: 's_5', realm: 'space', name: 'Interstellar Federation', description: 'Colony reaches outer galaxy, unlocking nebula visual theme.', tier: 5, cost: 680, resourceCost: 420, icon: 'Orbit', unlocked: false, bonusEffect: 'Nebula cosmic theme' },

  // Arcane
  { id: 'a_1', realm: 'arcane', name: 'Ley Line Attunement', description: 'Mind & meditation habits yield +25% Aether.', tier: 1, cost: 40, resourceCost: 20, icon: 'Brain', unlocked: true, bonusEffect: '+25% Mind Aether' },
  { id: 'a_2', realm: 'arcane', name: 'Alchemical Transmutation', description: 'Convert leftover realm resources into gold coins at 2:1 ratio.', tier: 2, cost: 90, resourceCost: 50, icon: 'Repeat', unlocked: false, bonusEffect: 'Resource conversion' },
  { id: 'a_3', realm: 'arcane', name: 'Astral Projection', description: 'View multi-day habit completion forecasts and heatmaps.', tier: 3, cost: 180, resourceCost: 105, icon: 'Eye', unlocked: false, bonusEffect: 'Astral forecast analytics' },
  { id: 'a_4', realm: 'arcane', name: 'Chrono-Stasis Ward', description: 'Freezes streak for up to 3 days when taking planned vacations.', tier: 4, cost: 340, resourceCost: 195, icon: 'Hourglass', unlocked: false, bonusEffect: 'Vacation streak lock' },
  { id: 'a_5', realm: 'arcane', name: 'Archmage Omniscience', description: 'Spire floats into celestial aether with prismatic aura.', tier: 5, cost: 620, resourceCost: 380, icon: 'Sparkles', unlocked: false, bonusEffect: 'Archmage celestial aura' },
];

const defaultDays: DayOfWeek[] = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'h-1',
    title: 'Morning Sunlight & Hydration',
    description: 'Drink a tall glass of water and get 10 minutes of natural sunlight.',
    category: 'Health',
    difficulty: 'Easy',
    targetTimeOfDay: 'Morning',
    targetRealm: 'garden',
    frequency: 'daily',
    scheduledDays: [...defaultDays],
    streak: 4,
    longestStreak: 12,
    totalCompletions: 28,
    archived: false,
    color: '#10b981',
    icon: 'Sun',
    completedToday: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h-2',
    title: 'Tactical Physical Training',
    description: '30 minutes of cardio, strength training, or high-intensity bodyweight exercises.',
    category: 'Fitness',
    difficulty: 'Hard',
    targetTimeOfDay: 'Afternoon',
    targetRealm: 'military',
    frequency: 'weekdays',
    scheduledDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
    streak: 6,
    longestStreak: 15,
    totalCompletions: 42,
    archived: false,
    color: '#3b82f6',
    icon: 'Dumbbell',
    completedToday: true,
    lastCompletedDate: new Date().toISOString().split('T')[0],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h-3',
    title: 'Deep Focus Work / Coding Sprint',
    description: '45 minutes of uninterrupted, distraction-free creative or software engineering work.',
    category: 'Career',
    difficulty: 'Epic',
    targetTimeOfDay: 'Morning',
    targetRealm: 'space',
    frequency: 'daily',
    scheduledDays: [...defaultDays],
    streak: 9,
    longestStreak: 21,
    totalCompletions: 65,
    archived: false,
    color: '#8b5cf6',
    icon: 'Code',
    completedToday: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h-4',
    title: 'Mindful Reading & Reflection',
    description: 'Read 15 pages of a book and journal 3 key takeaways or ideas.',
    category: 'Mind',
    difficulty: 'Medium',
    targetTimeOfDay: 'Evening',
    targetRealm: 'arcane',
    frequency: 'daily',
    scheduledDays: [...defaultDays],
    streak: 3,
    longestStreak: 18,
    totalCompletions: 34,
    archived: false,
    color: '#ec4899',
    icon: 'BookOpen',
    completedToday: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h-5',
    title: 'Community Check-in & Kindness',
    description: 'Message a friend, help a teammate, or tidy a shared space.',
    category: 'Routine',
    difficulty: 'Easy',
    targetTimeOfDay: 'Anytime',
    targetRealm: 'town',
    frequency: 'daily',
    scheduledDays: [...defaultDays],
    streak: 5,
    longestStreak: 14,
    totalCompletions: 39,
    archived: false,
    color: '#f59e0b',
    icon: 'Heart',
    completedToday: false,
    createdAt: new Date().toISOString(),
  },
];
